name: Docker Image Push

on:
  workflow_call:
    inputs:
      tag:
        description: Docker image tag
        required: false
        type: string
        default: 'latest'
      subdirectory:
        description: Subdirectory of the Dockerfile from project root
        required: false
        type: string
        default: ''
      
jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - id: lower-repo
      name: Lowercase Repository Name
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}/${{ inputs.subdirectory }}
      run: SOURCE_DATE_EPOCH=0 docker buildx build . --push --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ inputs.tag }}
