name: Docker Image Push

on:
  workflow_call:
    inputs:
      tag:
        description: Docker image tag
        required: false
        type: string
        default: 'latest'
      subdirectory:
        description: Subdirectory of the Dockerfile from project root
        required: false
        type: string
        default: ''
      
jobs:
  build_and_push_image:
    name: Build and Push Docker Image
    permissions:
        contents: read
        packages: write
    runs-on: ubuntu-latest
    steps:
    - id: lower-repo
      name: Lowercase Repository Name
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - name: Create NuGet Config
      run: |
        echo '<?xml version="1.0" encoding="utf-8"?>' > NuGet.Config
        echo '<configuration>' >> NuGet.Config
        echo '  <packageSources>' >> NuGet.Config
        echo '    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />' >> NuGet.Config
        echo '    <add key="github" value="https://nuget.pkg.github.com/Unicycle-Unicorn/index.json" />' >> NuGet.Config
        echo '  </packageSources>' >> NuGet.Config
        echo '  <packageSourceCredentials>' >> NuGet.Config
        echo '    <github>' >> NuGet.Config
        echo '      <add key="Username" value="${{ github.actor }}" />' >> NuGet.Config
        echo '      <add key="ClearTextPassword" value="${{ secrets.GITHUB_TOKEN }}" />' >> NuGet.Config
        echo '    </github>' >> NuGet.Config
        echo '  </packageSourceCredentials>' >> NuGet.Config
        echo '</configuration>' >> NuGet.Config
    - name: Build Docker Image
      working-directory: ${{ github.workspace }}/${{ inputs.subdirectory }}
      run: docker build . --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ inputs.tag }}
    - name: Login to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker Image
      run: docker push ghcr.io/${{ steps.lower-repo.outputs.repository }}:${{ inputs.tag }}
