name: Droplet SSH Docker Pull & Build

on:
  workflow_call:
      
jobs:
  ssh_droplet_update:
    name: SSH to Droplet and Update Docker
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: api.unicycleunicorn.net
          username: root
          password: ${{ secrets.droplet_password }}
          script: |
            docker compose ps -a
            docker compose pull
            docker compose up -d
            cat compose.yaml
            docker compose ps -a
